#!/sbin/runscript
# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
	use logger
}

JENKINS_USER="jenkins"
JENKINS_GROUP="jenkins"
JENKINS_HOME="/var/lib/jenkins-bin/home"
JENKINS_WAR="/var/lib/jenkins-bin/jenkins-bin.war"
JENKINS_PID="/var/run/jenkins-bin/jenkins-bin.pid"

start()	{
	ebegin "Starting jenkins-bin"

	JAVA_HOME="`java-config --jre-home`"
	JAVA="${JAVA_HOME}/bin/java"

	JENKINS_OPTS=""
	[ -n "${JENKINS_LOG_FILE}" ] && JENKINS_OPTS="${JENKINS_OPTS} --logfile=${JENKINS_LOG_FILE}"
	[ -n "${JENKINS_HTTP_PORT}" ] && JENKINS_OPTS="${JENKINS_OPTS} --httpPort=${JENKINS_HTTP_PORT}"

	start-stop-daemon \
		--start \
		--quiet \
		--background \
		--user ${JENKINS_USER}:${JENKINS_GROUP} \
		--make-pidfile \
		--pidfile "${JENKINS_PID}" \
		--exec "${JAVA}" -- -DJENKINS_HOME="${JENKINS_HOME}" -jar "${JENKINS_WAR}" ${JENKINS_OPTS}
	eend $?
}

stop()	{
	ebegin "Stopping jenkins-bin"
	start-stop-daemon \
		--stop \
		--quiet \
		--retry=60 \
		--pidfile "${JENKINS_PID}"
	eend $?
}

